site_name: Soft Culture Wiki
pages:
- Getting started: index.md
- Instruments: 'INS_01_Team_Instruments.md'
    - 'ChannelKit': 'ins_04_channelkit.md'
    - Beegit:
- About: about.md
- Инструменты: INS_01_Team_Instruments.md
- Выпуск постов: INS_05_Posts.md
theme: readthedocs
