site_name: Wiki Софт Культуры
docs_dir: markdown
site_dir: docs

pages:
- Getting started: index.md
- INSTRUMENTS:
    - Wrike: 'ins_10_wrike.md'
    - ChannelKit: 'ins_04_channelkit.md'
    - Airtable: 'ins_11_airtable.md'
    - Хранилище GD и S3: 'ins_16_storage_structure.md'
    - Others: 'ins_01_team_instruments.md'
- TASK GROUPS:
    - Meetings: 'ins_07_meetings.md'
    - Before: 'ins_08_before.md'
    - After: 'ins_09_after.md'
    - Promo: 'ins_11_promo.md'
- RULES:
    - Выпуск постов: 'ins_05_posts.md'
    - Правила хранения файлов: 'ins_13_storage_tasks.md'
    - Подготовка к занятию: 'ins_12_office_manager.md'
    - Обработка работ студентов: 'ins_15_students_works.md'
    - Обработка новых записей: 'ins_14_submissions.md'
    - Командные встречи: 'ins_17_meetings.md'
    - Сервисы куратора: 'ins_20_services.md'
- About: about.md

theme: readthedocs
extra_css: [extra.css]
extra_javascript: [passchecker_readthedocs.js]
