site_name: Wiki Софт Культуры
docs_dir: markdown
site_dir: docs

pages:
- Последние обновления: 'index.md'
- Введение: 'intro.md'
- Инструменты:
    - Wrike: 'ins_10_wrike.md'
    - ChannelKit: 'ins_04_channelkit.md'
    - Airtable: 'ins_11_airtable.md'
    - Хранилище GD и S3: 'ins_16_storage_structure.md'
    - Others: 'ins_01_team_instruments.md'
- Группы задач:
    - Meetings: 'ins_07_meetings.md'
    - Before: 'ins_08_before.md'
    - After: 'ins_09_after.md'
    - Promo: 'ins_11_promo.md'
- Правила:
    - Выпуск постов: 'ins_05_posts.md'
    - Правила хранения файлов: 'ins_13_storage_tasks.md'
    - Подготовка к занятию: 'ins_12_office_manager.md'
    - Обработка работ студентов: 'ins_15_students_works.md'
    - Обработка новых записей: 'ins_14_submissions.md'
    - Командные встречи: 'ins_17_meetings.md'
    - Сервисы куратора: 'ins_20_services.md'
- О площадке: 'about.md'

# Documentation and theme
theme: 'material'

# Options
markdown_extensions:
- admonition

extra:
  palette:
    primary: 'teal'
    accent: 'teal'
  disqus: 'disqus_softculture'

extra_css: [extra.css]
extra_javascript: [passchecker_readthedocs.js]
