site_name: Soft Culture Wiki
pages:
- Getting started: index.md
- INSTRUMENTS:
    - Wrike: 'ins_10_wrike.md'
    - ChannelKit: 'ins_04_channelkit.md'
    - Airtable: 'ins_11_promo.md'
    - Others: 'ins_01_team_instruments.md'
- TASK GROUPS:
    - Meetings: 'ins_07_meetings.md'
    - Before: 'ins_08_before.md'
    - After: 'ins_09_after.md'
    - Promo: 'ins_11_promo.md'
- RULES:
    - Выпуск постов: 'ins_05_posts.md'
- About: about.md

theme: readthedocs
extra_css: [extra.css]
